name: Deploy - dev

on:
  workflow_dispatch:

jobs:
  cloudflare:
    name: Deploy to Cloudflare
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: ${{ vars.APP_BASE_URL }}
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Deploy to Cloudflare
        uses: ./.github/actions/cloudflare-deploy
        with:
          cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          deploy_env: ${{ vars.DEPLOY_ENV }}
